# Template files have odd formatting so we exclude them a few times throughout
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-docstring-first
      exclude: .*/template-.*\.py
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: [--fix=lf]
  - repo: https://github.com/pycqa/isort
    rev: 5.3.0
    hooks:
      - id: isort
        exclude: .*/template-.*\.py
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      exclude: .*/template-.*\.py
